# Generated by Django 6.0.1 on 2026-07-16 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sinistre', models.CharField(max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('SOUMIS', 'Soumis'), ('ATTENTE_COMPLEMENTS', 'En attente de compléments'), ('ATTENTE_VALIDATION', 'En attente de validation'), ('A_CORRIGER', 'A corriger'), ('EN_COURS', 'En cours'), ('CLOTURE', 'Clôturé'), ('SANS_SUITE', 'Sans suite'), ('REOUVERT', 'Réouvert')], default='SOUMIS', max_length=30)),
                ('date_survenance', models.DateTimeField()),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('heure_approximative', models.TimeField()),
                ('circonstances', models.TextField()),
                ('quartier', models.CharField(max_length=150)),
                ('nature', models.CharField(choices=[('C', 'Corporel'), ('M', 'Matériel'), ('X', 'Mixte')], max_length=1)),
                ('precision', models.TextField(help_text='Circonstances exactes')),
                ('numero_point_vente', models.CharField(default='001', max_length=10)),
                ('lettre_derogation', models.FileField(blank=True, null=True, upload_to='sinistres/constats/')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='sinsitres/derogations/')),
                ('assure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistres', to=settings.AUTH_USER_MODEL)),
                ('prefecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_sinistres.prefecture')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_sinistres.region')),
            ],
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='sinistres/documents/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='gestion_sinistres.sinistre')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('annee', models.IntegerField()),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sinistre',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_sinistres.vehicule'),
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_sinistres.region')),
            ],
        ),
        migrations.AddField(
            model_name='sinistre',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_sinistres.ville'),
        ),
        migrations.AddField(
            model_name='prefecture',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_sinistres.ville'),
        ),
    ]
