# Generated by Django 6.0.1 on 2026-07-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_sinistres.region')),
            ],
        ),
        migrations.CreateModel(
            name='Sinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sinistre', models.CharField(max_length=20, unique=True)),
                ('date_survenance', models.DateTimeField()),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('heure_approximative', models.TimeField()),
                ('circonstances', models.TextField()),
                ('vehicule', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('nature', models.CharField(choices=[('C', 'Corporel'), ('M', 'Matériel'), ('X', 'Mixte')], max_length=1)),
                ('precision', models.TextField(help_text='Circonstances exactes')),
                ('numero_point_vente', models.CharField(default='001', max_length=10)),
                ('lettre_derogation', models.FileField(blank=True, null=True, upload_to='derogations/')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='piece_sinistres/')),
                ('prefecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_sinistres.prefecture')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_sinistres.region')),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_sinistres.ville')),
            ],
        ),
        migrations.AddField(
            model_name='prefecture',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_sinistres.ville'),
        ),
    ]
