# Generated by Django 6.0.1 on 2026-07-27 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('compte_active', models.BooleanField(default=False)),
                ('doit_changer_mot_de_passe', models.BooleanField(default=True)),
                ('tentatives_echouees', models.PositiveSmallIntegerField(default=0)),
                ('bloque_jusqu_a', models.DateTimeField(blank=True, null=True)),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_sinistres.agence')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_police', models.CharField(max_length=50, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('compte_active', models.BooleanField(default=False)),
                ('politique_confidentialite_acceptee', models.BooleanField(default=False)),
                ('tentatives_echouees', models.PositiveSmallIntegerField(default=0)),
                ('bloque_jusqu_a', models.DateTimeField(blank=True, null=True)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_sinistres.agence')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assure', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChefDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('compte_active', models.BooleanField(default=False)),
                ('doit_changer_mot_de_passe', models.BooleanField(default=True)),
                ('tentatives_echouees', models.PositiveSmallIntegerField(default=0)),
                ('bloque_jusqu_a', models.DateTimeField(blank=True, null=True)),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_sinistres.agence')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_quittance', models.CharField(max_length=50, unique=True)),
                ('type_contrat', models.CharField(blank=True, max_length=100, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('prime', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_retenu', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prix_valide', models.BooleanField(default=False)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quittances', to='gestion_sinistres.assure')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_sinistres.region')),
            ],
        ),
        migrations.CreateModel(
            name='Sinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_conducteur', models.CharField(max_length=100)),
                ('immatriculation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Immatriculation')),
                ('numero_sinistre', models.CharField(max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('SOUMIS', 'Soumis'), ('ATTENTE_COMPLEMENTS', 'En attente de compléments'), ('ATTENTE_VALIDATION', 'En attente de validation'), ('A_CORRIGER', 'A corriger'), ('EN_COURS', 'En cours'), ('CHEQUE_EMIS', 'Chèque émis'), ('CLOTURE', 'Clôturé'), ('SANS_SUITE', 'Sans suite'), ('REOUVERT', 'Réouvert')], default='SOUMIS', max_length=30)),
                ('agent_traitant', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_assure', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="Numéro d'assuré")),
                ('montant_estime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prix_retenu', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('attestation_generee', models.BooleanField(default=False)),
                ('date_attestation', models.DateTimeField(blank=True, null=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('indemnisation_validee', models.BooleanField(default=False)),
                ('date_survenance', models.DateTimeField()),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('heure_approximative', models.TimeField()),
                ('circonstances', models.TextField()),
                ('quartier', models.CharField(max_length=150)),
                ('nature', models.CharField(choices=[('C', 'Corporel'), ('M', 'Matériel'), ('X', 'Mixte')], max_length=1)),
                ('numero_point_vente', models.CharField(default='001', max_length=10)),
                ('lettre_derogation', models.FileField(blank=True, null=True, upload_to='sinistres/derogations/')),
                ('autre_vehicule_implique', models.BooleanField(default=False)),
                ('vehicule_adverse_immatriculation', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicule_adverse_marque', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicule_adverse_modele', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_blesses', models.PositiveSmallIntegerField(default=0)),
                ('nombre_morts', models.PositiveSmallIntegerField(default=0)),
                ('assure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistres', to=settings.AUTH_USER_MODEL)),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_sinistres.commune')),
                ('quittance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_sinistres.quittance')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_sinistres.region')),
            ],
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='sinistres/documents/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='gestion_sinistres.sinistre')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(max_length=100)),
                ('banque_cheque', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('beneficiaire_nom', models.CharField(max_length=100)),
                ('beneficiaire_prenoms', models.CharField(max_length=150)),
                ('beneficiaire_telephone', models.CharField(max_length=20)),
                ('date_emission', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('nom_retirant', models.CharField(blank=True, help_text='Si différent du bénéficiaire', max_length=150, null=True)),
                ('type_piece_retirant', models.CharField(blank=True, choices=[('CNI', "Carte Nationale d'Identité"), ('PERMIS', 'Permis de conduire'), ('PASSEPORT', 'Passeport')], max_length=20, null=True)),
                ('numero_piece_retirant', models.CharField(blank=True, max_length=50, null=True)),
                ('piece_identite_retirant', models.FileField(blank=True, null=True, upload_to='paiements/pieces_identite/')),
                ('statut', models.CharField(choices=[('EMIS', 'Emis'), ('DISPONIBLE', 'Prêt pour retrait'), ('RETIRE', 'Retiré'), ('ANNULE', 'Annulé')], default='EMIS', max_length=20)),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion_sinistres.sinistre')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gestion_sinistres.sinistre')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=50)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('commentaires', models.TextField(blank=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='gestion_sinistres.sinistre')),
            ],
        ),
        migrations.CreateModel(
            name='EtapeSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_etape', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='gestion_sinistres.sinistre')),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(max_length=50, unique=True, verbose_name='Numéro du chèque')),
                ('banque_emettrice', models.CharField(max_length=100, verbose_name='Banque émettrice')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('beneficiaire', models.CharField(max_length=200, verbose_name='Nom du bénéficiaire')),
                ('statut', models.CharField(choices=[('EN_PREPARATION', 'En cours de préparation'), ('DISPONIBLE', 'Prêt pour retrait'), ('RETIRE', "Retiré par l'assuré"), ('ANNULE', 'Annulé')], default='EN_PREPARATION', max_length=20)),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_disponibilite', models.DateField(blank=True, null=True, verbose_name='Date de disponibilité')),
                ('date_retrait', models.DateField(blank=True, null=True, verbose_name='Date de retrait')),
                ('agent_emetteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agent ayant émis le chèque')),
                ('sinistre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cheque', to='gestion_sinistres.sinistre', verbose_name='Sinistre associé')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(blank=True, max_length=50, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to=settings.AUTH_USER_MODEL)),
                ('quittance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='gestion_sinistres.quittance')),
            ],
        ),
        migrations.AddField(
            model_name='sinistre',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_sinistres.vehicule'),
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_sinistres.commune')),
            ],
        ),
        migrations.AddField(
            model_name='sinistre',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_sinistres.ville'),
        ),
        migrations.AddConstraint(
            model_name='quittance',
            constraint=models.CheckConstraint(condition=models.Q(('prix_retenu__lte', models.F('prime'))), name='check_prix_retenu_lte_prime'),
        ),
        migrations.AddConstraint(
            model_name='quittance',
            constraint=models.CheckConstraint(condition=models.Q(('date_debut__lte', models.F('date_fin'))), name='check_quittance_date_debut_lte_date_fin'),
        ),
    ]
