# Generated by Django 6.0.1 on 2026-07-15 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistre',
            name='lettre_derogation',
            field=models.FileField(default=None, upload_to='sinistres/constats/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='sinsitres/derogations/'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='quartier',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('annee', models.IntegerField()),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_sinistres.vehicule'),
        ),
    ]
