# Generated by Django 6.0.1 on 2026-07-27 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='code',
        ),
        migrations.AddField(
            model_name='agence',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_sinistres.ville'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
