# Generated by Django 6.0.1 on 2026-07-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0002_historiquesinistre_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='immatriculation',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinistre',
            name='n_police',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinistre',
            name='nom_conducteur',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
