# Generated by Django 6.0.1 on 2026-07-16 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0002_alter_sinistre_lettre_derogation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='sinistres/documents/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='gestion_sinistres.sinistre')),
            ],
        ),
    ]
