# Generated by Django 6.0.1 on 2026-07-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0002_remove_agence_code_agence_ville_alter_agence_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='vehicule_adverse_compagnie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Compagnie d'assurance (véhicule adverse)"),
        ),
    ]
