# Generated by Django 6.0.1 on 2026-07-16 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0003_sinistre_immatriculation_sinistre_n_police_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinistre',
            name='piece_jointe',
        ),
        migrations.AddField(
            model_name='sinistre',
            name='agent_traitant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='lettre_derogation',
            field=models.FileField(blank=True, null=True, upload_to='sinistres/derogations/'),
        ),
        migrations.CreateModel(
            name='EtapeSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_etape', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='gestion_sinistres.sinistre')),
            ],
        ),
    ]
