# Generated by Django 6.0.1 on 2026-07-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0003_piecejointe'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='statut',
            field=models.CharField(choices=[('SOUMIS', 'Soumis'), ('ATTENTE', 'En attente de validation'), ('EN_COURS', 'En cours'), ('CLOTURE', 'Clôturé'), ('SANS_SUITE', 'Sans suite')], default='SOUMIS', max_length=15),
        ),
    ]
