# Generated by Django 6.0.1 on 2026-07-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0003_sinistre_vehicule_adverse_compagnie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinistre',
            name='numero_assure',
        ),
        migrations.AlterField(
            model_name='paiement',
            name='numero_cheque',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
