# Generated by Django 6.0.1 on 2026-07-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0004_remove_sinistre_piece_jointe_sinistre_agent_traitant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='montant_estime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
