# Generated by Django 6.0.1 on 2026-07-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0004_remove_sinistre_numero_assure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistre',
            name='statut',
            field=models.CharField(choices=[('SOUMIS', 'Soumis'), ('ATTENTE_COMPLEMENTS', 'En attente de compléments'), ('ATTENTE_VALIDATION', 'En attente de validation'), ('A_CORRIGER', 'A corriger'), ('EN_COURS', 'En cours'), ('CLOTURE', 'Clôturé'), ('SANS_SUITE', 'Sans suite'), ('REOUVERT', 'Réouvert')], default='SOUMIS', max_length=30),
        ),
    ]
