# Generated by Django 6.0.1 on 2026-07-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0004_sinistre_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistre',
            name='lettre_derogation',
            field=models.FileField(blank=True, null=True, upload_to='sinistres/constats/'),
        ),
    ]
