# Generated by Django 6.0.1 on 2026-07-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0006_assure'),
    ]

    operations = [
        migrations.AddField(
            model_name='assure',
            name='compte_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assure',
            name='politique_confidentialite_acceptee',
            field=models.BooleanField(default=False),
        ),
    ]
