# Generated by Django 6.0.1 on 2026-08-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0006_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='niveau_responsabilite',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinistre',
            name='pv_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='taux_responsabilite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
