# Generated by Django 6.0.1 on 2026-08-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0007_sinistre_niveau_responsabilite_sinistre_pv_verifie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='contact_declarant',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Contact du déclarant'),
        ),
    ]
