# Generated by Django 6.0.1 on 2026-07-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0008_agence_assure_agence_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=True),
        ),
    ]
