# Generated by Django 6.0.1 on 2026-08-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0008_sinistre_contact_declarant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistre',
            name='contact_declarant',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Contact du déclarant'),
        ),
    ]
