# Generated by Django 6.0.1 on 2026-07-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0009_agent_doit_changer_mot_de_passe'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='banque_cheque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='beneficiaire_nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='beneficiaire_prenoms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='beneficiaire_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='date_emission_cheque',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='montant_cheque',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='numero_cheque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='prix_retenu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
