# Generated by Django 6.0.1 on 2026-08-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0009_alter_sinistre_contact_declarant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='dommages',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
