# Generated by Django 6.0.1 on 2026-08-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0010_sinistre_dommages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sinistre',
            old_name='dommages',
            new_name='dommage',
        ),
    ]
