# Generated by Django 6.0.1 on 2026-08-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0011_rename_dommages_sinistre_dommage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistre',
            name='niveau_responsabilite',
            field=models.TextField(blank=True),
        ),
    ]
