# Generated by Django 6.0.1 on 2026-07-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0011_chefdepartement'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefdepartement',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=True),
        ),
    ]
