# Generated by Django 6.0.1 on 2026-07-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0012_chefdepartement_doit_changer_mot_de_passe'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='attestation_generee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='date_attestation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
