# Generated by Django 6.0.1 on 2026-08-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0012_alter_sinistre_niveau_responsabilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistre',
            name='nature',
            field=models.CharField(blank=True, choices=[('C', 'Corporel'), ('M', 'Matériel'), ('X', 'Mixte')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='niveau_responsabilite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='numero_sinistre',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='quittance',
        ),
        migrations.AddField(
            model_name='sinistre',
            name='quittance',
            field=models.ManyToManyField(blank=True, related_name='sinistres', to='gestion_sinistres.quittance'),
        ),
    ]
