# Generated by Django 6.0.1 on 2026-08-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0013_alter_sinistre_nature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sinistre',
            old_name='quittance',
            new_name='quittances',
        ),
    ]
