# Generated by Django 6.0.1 on 2026-07-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0013_sinistre_attestation_generee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='motif_sans_suite',
            field=models.TextField(blank=True, null=True),
        ),
    ]
