# Generated by Django 6.0.1 on 2026-08-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0014_rename_quittance_sinistre_quittances'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='est_declarant_tiers',
            field=models.BooleanField(default=False, verbose_name='Déclaration faite par un tiers'),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='nom_declarant',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom déclarant (Tiers)'),
        ),
    ]
