# Generated by Django 6.0.1 on 2026-07-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0014_sinistre_motif_sans_suite'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='indemnisation_validee',
            field=models.BooleanField(default=False),
        ),
    ]
