# Generated by Django 6.0.1 on 2026-07-20 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0015_sinistre_indemnisation_validee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_quittance', models.CharField(max_length=50, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('prime', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quittances', to='gestion_sinistres.assure')),
            ],
        ),
        migrations.AddField(
            model_name='sinistre',
            name='quittance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_sinistres.quittance'),
        ),
    ]
