# Generated by Django 6.0.1 on 2026-08-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0015_sinistre_est_declarant_tiers_sinistre_nom_declarant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='email_declarant',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du déclarant'),
        ),
    ]
