# Generated by Django 6.0.1 on 2026-08-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0016_sinistre_email_declarant'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefdepartement',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/chefs/', verbose_name='Signature'),
        ),
    ]
