# Generated by Django 6.0.1 on 2026-07-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0016_quittance_sinistre_quittance'),
    ]

    operations = [
        migrations.AddField(
            model_name='assure',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quittance',
            name='immatriculation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quittance',
            name='marque_vehicule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quittance',
            name='type_contrat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
