# Generated by Django 6.0.1 on 2026-07-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0017_assure_telephone_quittance_immatriculation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefdepartement',
            name='compte_active',
            field=models.BooleanField(default=False),
        ),
    ]
