# Generated by Django 6.0.1 on 2026-07-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0018_chefdepartement_compte_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quittance',
            name='immatriculation',
        ),
        migrations.RemoveField(
            model_name='quittance',
            name='marque_vehicule',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='modele',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='proprietaire',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='quittance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='gestion_sinistres.quittance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='marque',
            field=models.CharField(max_length=100),
        ),
    ]
