# Generated by Django 6.0.1 on 2026-08-21 10:25
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0019_message_lu'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE gestion_sinistres_sinistre CHANGE COLUMN vehicule_adverse_modele vehicule_adverse_categorie varchar(50) NULL;",
                    reverse_sql="ALTER TABLE gestion_sinistres_sinistre CHANGE COLUMN vehicule_adverse_categorie vehicule_adverse_modele varchar(50) NULL;",
                ),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name='sinistre',
                    old_name='vehicule_adverse_modele',
                    new_name='vehicule_adverse_categorie',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE gestion_sinistres_vehicule CHANGE COLUMN modele categorie varchar(50) NULL;",
                    reverse_sql="ALTER TABLE gestion_sinistres_vehicule CHANGE COLUMN categorie modele varchar(50) NULL;",
                ),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name='vehicule',
                    old_name='modele',
                    new_name='categorie',
                ),
            ],
        ),
    ]