# Generated by Django 6.0.1 on 2026-07-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0020_vehicule_annee_vehicule_modele_vehicule_proprietaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quittance',
            name='prix_retenu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='quittance',
            constraint=models.CheckConstraint(condition=models.Q(('prix_retenu__lte', models.F('prime'))), name='check_prix_retenu_lte_prime'),
        ),
        migrations.AddConstraint(
            model_name='quittance',
            constraint=models.CheckConstraint(condition=models.Q(('date_debut__lte', models.F('date_fin'))), name='check_quittance_date_debut_lte_date_fin'),
        ),
    ]
