# Generated by Django 6.0.1 on 2026-08-21 10:28
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0020_rename_vehicule_adverse_modele_sinistre_vehicule_adverse_categorie_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE gestion_sinistres_quittance CHANGE COLUMN type_contrat branche varchar(100) NULL;",
                    reverse_sql="ALTER TABLE gestion_sinistres_quittance CHANGE COLUMN branche type_contrat varchar(100) NULL;",
                ),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name='quittance',
                    old_name='type_contrat',
                    new_name='branche',
                ),
            ],
        ),
    ]