# Generated by Django 6.0.1 on 2026-07-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0021_quittance_prix_retenu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinistre',
            name='precision',
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='immatriculation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Immatriculation'),
        ),
    ]
