# Generated by Django 6.0.1 on 2026-07-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0022_remove_sinistre_precision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinistre',
            name='n_police',
        ),
    ]
