# Generated by Django 6.0.1 on 2026-07-24 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0023_remove_sinistre_n_police'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinistre',
            name='attestation_generee',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='banque_cheque',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='beneficiaire_nom',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='beneficiaire_prenoms',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='beneficiaire_telephone',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='date_attestation',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='date_emission_cheque',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='indemnisation_validee',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='montant_cheque',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='motif_sans_suite',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='numero_cheque',
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(max_length=50, unique=True, verbose_name='Numéro du chèque')),
                ('banque_emettrice', models.CharField(max_length=100, verbose_name='Banque émettrice')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('beneficiaire', models.CharField(max_length=200, verbose_name='Nom du bénéficiaire')),
                ('statut', models.CharField(choices=[('EN_PREPARATION', 'En cours de préparation'), ('DISPONIBLE', 'Prêt pour retrait'), ('RETIRE', "Retiré par l'assuré"), ('ANNULE', 'Annulé')], default='EN_PREPARATION', max_length=20)),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_disponibilite', models.DateField(blank=True, null=True, verbose_name='Date de disponibilité')),
                ('date_retrait', models.DateField(blank=True, null=True, verbose_name='Date de retrait')),
                ('agent_emetteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agent ayant émis le chèque')),
                ('sinistre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cheque', to='gestion_sinistres.sinistre', verbose_name='Sinistre associé')),
            ],
        ),
    ]
