# Generated by Django 6.0.1 on 2026-07-24 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0024_remove_sinistre_attestation_generee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistre',
            name='statut',
            field=models.CharField(choices=[('SOUMIS', 'Soumis'), ('ATTENTE_COMPLEMENTS', 'En attente de compléments'), ('ATTENTE_VALIDATION', 'En attente de validation'), ('A_CORRIGER', 'A corriger'), ('EN_COURS', 'En cours'), ('CHEQUE_EMIS', 'Chèque émis'), ('CLOTURE', 'Clôturé'), ('SANS_SUITE', 'Sans suite'), ('REOUVERT', 'Réouvert')], default='SOUMIS', max_length=30),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(max_length=100)),
                ('banque_cheque', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('beneficiaire_nom', models.CharField(max_length=100)),
                ('beneficiaire_prenoms', models.CharField(max_length=150)),
                ('beneficiaire_telephone', models.CharField(max_length=20)),
                ('date_emission', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion_sinistres.sinistre')),
            ],
        ),
    ]
