# Generated by Django 6.0.1 on 2026-07-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0025_alter_sinistre_statut_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='quittance',
            name='prix_valide',
            field=models.BooleanField(default=False),
        ),
    ]
