# Generated by Django 6.0.1 on 2026-07-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0026_quittance_prix_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='attestation_generee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='date_attestation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='indemnisation_validee',
            field=models.BooleanField(default=False),
        ),
    ]
