# Generated by Django 6.0.1 on 2026-07-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0027_sinistre_attestation_generee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
