# Generated by Django 6.0.1 on 2026-07-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0028_sinistre_date_cloture'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EMIS', 'Emis'), ('DISPONIBLE', 'Prêt pour retrait'), ('RETIRE', 'Retiré'), ('ANNULE', 'Annulé')], default='EMIS', max_length=20),
        ),
    ]
