# Generated by Django 6.0.1 on 2026-07-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sinistres', '0029_paiement_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bloque_jusqu_a',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='tentatives_echouees',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chefdepartement',
            name='bloque_jusqu_a',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chefdepartement',
            name='tentatives_echouees',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paiement',
            name='nom_retirant',
            field=models.CharField(blank=True, help_text='Si différent du bénéficiaire', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero_piece_retirant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='piece_identite_retirant',
            field=models.FileField(blank=True, null=True, upload_to='paiements/pieces_identite/'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='type_piece_retirant',
            field=models.CharField(blank=True, choices=[('CNI', "Carte Nationale d'Identité"), ('PERMIS', 'Permis de conduire'), ('PASSEPORT', 'Passeport')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='autre_vehicule_implique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='bloque_jusqu_a',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='nombre_blesses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='nombre_morts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='numero_assure',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="Numéro d'assuré"),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='tentatives_echouees',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='vehicule_adverse_immatriculation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='vehicule_adverse_marque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='vehicule_adverse_modele',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
